development:
  adapter:  postgresql
  host:     ''
  encoding: unicode
  database: crowdcensus_development
  pool:     5
  username: misigno
  template: template0

test:
  adapter:  postgresql
  host:     ''
  encoding: unicode
  database: crowdcensus_test
  pool:     5
  username: misigno
  template: template0

production:
  adapter:  postgres
  host:     ''
  encoding: unicode
  database: crowdcensus_production
  pool:     5
  username: misigno
  template: template0
