development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: fifty5018
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: www.crowdcensus.me
  secret_key_base: 177f9b9be1e1e44e9963d481aff2589a9093042a2d846895b592f453012b561901ecc67ab0f2fe2a9916c94e1c7c2ec12dfb5404d0d645ddd483fe562fa06f92

test:
  domain_name: example.com
  secret_key_base: 2081443540ec38ca9a2923ff64d5bcb1dff9c0f75d1468b3af0a160c5413e1553a0c29d1441278b774c6649027b200ecdd53c876bb1820d1826150d42b4f95eb

production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
